/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/new-alarm`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/alarms` | `/alarms`; params?: Router.UnknownInputParams; } | { pathname: `/context/AlarmsContext`; params?: Router.UnknownInputParams; } | { pathname: `/lib/notifications`; params?: Router.UnknownInputParams; } | { pathname: `/lib/sound`; params?: Router.UnknownInputParams; } | { pathname: `/lib/storage`; params?: Router.UnknownInputParams; } | { pathname: `/lib/taskManager`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/new-alarm`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/alarms` | `/alarms`; params?: Router.UnknownOutputParams; } | { pathname: `/context/AlarmsContext`; params?: Router.UnknownOutputParams; } | { pathname: `/lib/notifications`; params?: Router.UnknownOutputParams; } | { pathname: `/lib/sound`; params?: Router.UnknownOutputParams; } | { pathname: `/lib/storage`; params?: Router.UnknownOutputParams; } | { pathname: `/lib/taskManager`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/new-alarm${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/alarms${`?${string}` | `#${string}` | ''}` | `/alarms${`?${string}` | `#${string}` | ''}` | `/context/AlarmsContext${`?${string}` | `#${string}` | ''}` | `/lib/notifications${`?${string}` | `#${string}` | ''}` | `/lib/sound${`?${string}` | `#${string}` | ''}` | `/lib/storage${`?${string}` | `#${string}` | ''}` | `/lib/taskManager${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/new-alarm`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/alarms` | `/alarms`; params?: Router.UnknownInputParams; } | { pathname: `/context/AlarmsContext`; params?: Router.UnknownInputParams; } | { pathname: `/lib/notifications`; params?: Router.UnknownInputParams; } | { pathname: `/lib/sound`; params?: Router.UnknownInputParams; } | { pathname: `/lib/storage`; params?: Router.UnknownInputParams; } | { pathname: `/lib/taskManager`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
